### PR TITLE
Make it pretty!

### PR DESCRIPTION
**Pull request by thelastnode**
Add Bootstrap from Twitter and style the layout. More coming soon.

### CODE REVIEW

**Comment by skalnik** [comment]
:heart: Twitter Bootstrap. So fucking sexy and easy to use. Good call bringing that in, even if I haven't even touched this project.

**Comment by thelastnode** [comment]
Some previews:
Logged out page -
img

Logged in page -
img

**Comment by skalnik** [comment]
:metal:

**Comment by thelastnode** [comment]
Replaced by #52.

**Pull request closed without merging**
