### PR TITLE
Export models in ./lib/models.js

### PR DESCRIPTION
**Pull request by thelastnode**
Now we don't need to use mongoose to access the models anymore.

### CODE REVIEW

**Comment by ash211** [comment]
Hey!  No merging your own pull requests.  Code review!

This looks good, merge it :)

**Comment by thelastnode** [comment]
Wasn't sure how hardcore involved you were going to be, are you still going to be active? If so, I won't merge my own, otherwise you can review retroactively and we can revert.

**Comment by ash211** [comment]
Decently active I think.  I'm really liking node.js :)

**Comment by thelastnode** [comment]
Okay cool, I'll stop approving my own pull requests, up till a day or so :)

**Pull request merged**
